# Generated by Django 3.2.12 on 2023-01-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogentry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'ordering': ['-date']},
        ),
    ]
