# Generated by Django 3.2.12 on 2023-01-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blogentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={},
        ),
    ]
