# Generated by Django 4.0.8 on 2023-02-04 16:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0008_alter_blogentry_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaryEntry',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Post date')),
                ('body', wagtail.fields.StreamField([('commentary_block', wagtail.blocks.StructBlock([('column_1', wagtail.blocks.RichTextBlock()), ('column_2', wagtail.blocks.RichTextBlock())])), ('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('indented_paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
